---
title: "Talks"
---

## Other Talks

::: {.talk-item}
<div class="talk-title"><a href="files/slides/2024_04_29_DFO_seminar_intro_RO.pdf">A Tutorial on Riemannian Optimization</a></div>
<div class="meta">Derivative-Free Optimization Seminar held by [Liyuan Cao](https://liyuancao.github.io/), Peking University, Beijing, China, April 2024.</div>
:::

::: {.talk-item}
<div class="talk-title"><a href="files/slides/2024_06_06_SUEP_CAS.pdf">Riemannian Interior Point Methods for Constrained Optimization on Manifolds</a></div>
<div class="meta">Seminar held by [Xiaojing Zhu (竺筱晶)](https://slxy.shiep.edu.cn/8d/b6/c3280a232886/page.htm), Shanghai University of Electric Power, online, June 5, 2024.</div>
:::

::: {.talk-item}
<div class="talk-title"><a href="files/slides/2024_06_06_SUEP_CAS.pdf">Riemannian Interior Point Methods for Constrained Optimization on Manifolds</a></div>
<div class="meta">Seminar held by Li Zhang (章丽), Institute of Computational Mathematics and Scientific/Engineering Computing, Academy of Mathematics and Systems Science, CAS, June 6, 2024.</div>
:::

## Oral Presentations at International Conferences

::: {.talk-item}
<div class="talk-title"><a href="files/slides/2023_08_24_ICIAM2023.pdf">Riemannian Interior Point Methods for Constrained Optimization on Manifolds</a></div>
<div class="meta">[The 10th International Congress on Industrial and Applied Mathematics (ICIAM)](https://iciam2023.org/registered_data?id=01064), Waseda University, Tokyo, Japan, August 2023.</div>
:::

::: {.talk-item}
<div class="talk-title"><a href="files/slides/SeattleSIAMOP.pdf">Interior Point Methods for Nonlinear Optimization on Riemannian Manifolds</a></div>
<div class="meta">[SIAM Conference on Optimization (OP23)](https://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=75974), Seattle, USA, June 2023.</div>
:::

::: {.talk-item}
<div class="talk-title"><a href="files/slides/2022_12_4_IWCO.pdf">Riemannian Interior Point Methods for Constrained Optimization on Manifolds</a></div>
<div class="meta">[International Workshop on Continuous Optimization](http://www.opt.c.titech.ac.jp/DecemberWorkshop/schedule.html), Tokyo (virtual), December 2022.</div>
:::

::: {.talk-item}
<div class="talk-title"><a href="files/slides/2021_07_22_SIAM_OP21.pdf">Completely Positive Factorization via Orthogonality Constrained Problem</a></div>
<div class="meta">[SIAM Conference on Optimization (OP21)](https://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=71097), Hong Kong (virtual), July 2021.</div>
:::

## Oral Presentations at Domestic Conferences in Japan

::: {.talk-item}
<div class="talk-title"><a href="files/slides/2023_05_20_RAOTA.pdf">Riemannian Interior Point Methods for Constrained Optimization on Manifolds</a></div>
<div class="meta">[Research Association of Optimization Theory and Algorithms (RAOTA): Gathering of Young Researchers for the Future 2023](https://orsj.org/raota/wp-content/uploads/sites/16/2023/05/tsukuba23program.pdf), University of Tsukuba, Tsukuba, Ibaraki, May 2023.</div>
:::

::: {.talk-item}
<div class="talk-title"><a href="files/slides/2023_03_07_OR.pdf">Riemannian Interior Point Methods for Constrained Optimization on Manifolds</a></div>
<div class="meta">[The 2023 spring national conference of operations research society of Japan](https://orsj.org/nc2023s/wp-content/uploads/sites/14/2023/01/detail.pdf), Chuo University, Tokyo, March 2023.</div>
:::

::: {.talk-item}
<div class="talk-title"><a href="files/slides/2022_09_08_JSIAM2022.pdf">On the Global Convergence of Riemannian Interior Point Method</a></div>
<div class="meta">[The 2022 autumn national conference of operations research society of Japan](https://orsj.org/nc2022f/wp-content/uploads/sites/13/2022/09/program2022f.pdf), Niigata (virtual), September 2022.</div>
:::

::: {.talk-item}
<div class="talk-title"><a href="files/slides/2022_09_08_JSIAM2022.pdf">On the Global Convergence of Riemannian Interior Point Method</a></div>
<div class="meta">[The Japan society for industrial and applied mathematics 2022 annual meeting](https://conference.wdc-jp.com/jsiam/2022/program/program_flash.html), Hokkaido University, Sapporo, Hokkaido, September 2022.</div>
:::

::: {.talk-item}
<div class="talk-title"><a href="files/slides/2022_03_17_OR.pdf">Superlinear and Quadratic Convergence of Riemannian Interior Point Methods</a></div>
<div class="meta">[The 2022 spring national conference of operations research society of Japan](https://orsj.org/nc2022s/wp-content/uploads/sites/12/2022/02/2022s-program_all.pdf), Gunma University, Gunma (virtual), March 2022.</div>
:::

::: {.talk-item}
<div class="talk-title"><a href="files/slides/2021_08_19_RIMS.pdf">Application of Smoothing Methods for Completely Positive Matrices via Orthogonality Constrained Problem</a></div>
<div class="meta">[Kyoto University mathematical analysis research institute research meeting](https://sites.google.com/view/rimsoptimization2021/%E3%83%9B%E3%83%BC%E3%83%A0), Kyoto University, Kyoto (virtual), August 2021.</div>
:::

::: {.talk-item}
<div class="talk-title"><a href="files/slides/20210302_OR21_spring.pdf">Completely Positive Factorization via Orthogonality Constrained Problem</a></div>
<div class="meta">[The 2021 spring national conference of operations research society of Japan](https://www.orsj.or.jp/nc/2021s/?page_id=20), Tokyo Institute of Technology, Tokyo (virtual), March 2021.</div>
:::

::: {.talk-item}
<div class="talk-title"><a href="files/slides/RIMSmeeting20200824.pdf">A New Approach to the Recognition Problem of Completely Positive Matrices</a></div>
<div class="meta">[Kyoto University mathematical analysis research institute research meeting](https://sites.google.com/view/akiyoshishioura/rimsmeeting2020), Kyoto University, Kyoto (virtual), August 2020.</div>
:::

## Poster Presentations

::: {.talk-item}
<div class="talk-title"><a href="files/posters/2023_08_09_summer_scholl_poster.pdf">Riemannian Interior Point Methods for Constrained Optimization on Manifolds</a></div>
<div class="meta">[Summer School on Continuous Optimization and Related Fields](https://www.ism.ac.jp/~mirai/sscoke/2023/), Institute of Statistical Mathematics, Tokyo, Japan, August 2023.</div>
:::

::: {.talk-item}
<div class="talk-title"><a href="files/posters/2023_03_22_jst_poster.pdf">Riemannian Interior Point Methods for Manifold Optimization</a></div>
<div class="meta">2022 SPRING Fellowship Research Meeting, Tsukuba, Ibaraki, Japan, March 2023.</div>
:::

::: {.talk-item}
<div class="talk-title"><a href="files/posters/2022_03_22_jst_poster.pdf">Riemannian Optimization and Its Applications</a></div>
<div class="meta">2021 SPRING Fellowship Research Meeting, Tsukuba, Ibaraki, Japan, March 2022.</div>
:::
