---
title: "Teaching"
description: "Teaching by Zhijian Lai"
---

## PKU Advanced Mathematics (Class B), 2024--2025

北京大学 24--25 学年高数 B 讲义（2025 年 6 月 8 日汇总）。

- [北京大学《高等数学》(B) (一) 2024 年秋学期 · 全部内容合订版 (1--6 章)](https://gitee.com/galvin-lai/Advanced-Mathematics-Class-B-07/raw/master/AM-B-1-PKU-ALL.pdf). Course homepage: [AM-B-1](https://gitee.com/galvin-lai/Advanced-Mathematics-Class-B-07).
- [北京大学《高等数学》(B) (二) 2025 年春学期 · 全部内容合订版 (7--12 章)](https://gitee.com/galvin-lai/Advanced-Mathematics-Class-B2-07/raw/master/AM-B-2-PKU-ALL.pdf). Course homepage: [AM-B-2](https://gitee.com/galvin-lai/Advanced-Mathematics-Class-B2-07).

## Teaching Assistant, University of Tsukuba

I will be a teaching assistant for:

- FH61141 [Society and Optimization](https://kdb.tsukuba.ac.jp/syllabi/2023/FH61141/jpn/0), 2023 Fall.

I was a teaching assistant for:

- FH35012 [Problem Identification and Resolution](https://kdb.tsukuba.ac.jp/syllabi/2023/FH35012/jpn/0), 2022 Fall.
- FH61141 [Society and Optimization](https://kdb.tsukuba.ac.jp/syllabi/2023/FH61141/jpn/0), 2022 Fall.
- 0AL5100 [Supply Chain Management](https://kdb.tsukuba.ac.jp/syllabi/2021/0AL5100/jpn/0), 2021 Fall.

## Mathematics Tutoring for Graduate Admission Examination

I was officially employed as a subject tutor to support international students preparing for [the MPPS and MSE entrance exams](https://www.sk.tsukuba.ac.jp/PPS/en/ap/), Graduate School for Policy and Planning Sciences, University of Tsukuba.

- Linear Algebra for entrance exams in August 2021.
- Calculus for entrance exams in December 2019.
- Calculus for entrance exams in August 2019.

During the COVID-19 pandemic, I uploaded course videos to [Bilibili](https://space.bilibili.com/16115578) to help students in need.

## University-High School Collaboration Project

This project was supported by the Japan Science and Technology Agency. Its aim was to enable high school students to identify problems within their living environment and propose solutions using optimization models, such as MILP, and solvers such as Xpress and Gurobi.

From 2019 to 2021, I served as a TA and guided groups working on the following topics:

- Developing a self-study schedule program to maximize efficiency, 2021.
- Selecting evacuation shelters during disasters, 2020.
- Leveling out the number of people using school cafeterias, 2019.
- Easing congestion by determining stops on the Tobu Isezaki Line, 2019.
