---
title: "软件"
---

## 流形优化求解器

虽然 [Manopt](https://www.manopt.org/tutorial.html) 是广泛使用的黎曼流形优化求解器，但一些问题需要处理非光滑目标函数或额外约束。下面的项目沿着这一方向进行扩展。

::: {.software-item}
<div class="software-title">RieSmooth：黎曼流形上的非光滑目标函数</div>

**RieSmooth** 是一个面向非光滑黎曼优化问题的通用黎曼光滑算法，用于求解

<div class="math-display">min<sub>x &isin; M</sub> f(x)</div>

其中 <span class="math-inline">M</span> 可以是 [Manopt](https://www.manopt.org/tutorial.html) 中已有的任意流形，<span class="math-inline">f: M &rarr; R</span> 是非光滑函数。

<div class="link-row"><a class="pill-link" href="https://github.com/GALVINLAI/General-Riemannian-Smoothing-Method">代码与说明</a></div>

参考文献：Zhijian Lai, Akiko Yoshise. *Completely positive factorization by a Riemannian smoothing method*. Computational Optimization and Applications, 83, 933--966, 2022. <https://doi.org/10.1007/s10589-022-00417-4>

示例包括完全正矩阵分解（CPfact）、寻找子空间中的最稀疏向量（FSV）和鲁棒低秩矩阵补全（RMC）。
:::

::: {.software-item}
<div class="software-title">RIPM：黎曼流形上的额外约束</div>

**Riemannian Interior Point Methods (RIPM)** 是一个原始-对偶内点求解器，用于求解带等式和不等式约束的黎曼流形非线性优化问题：

<div class="math-display">
  <div>min<sub>x &isin; M</sub> f(x)</div>
  <div>s.t. &nbsp; h(x) = 0, &nbsp; g(x) &le; 0,</div>
</div>

其中 <span class="math-inline">M</span> 可以是 [Manopt](https://www.manopt.org/tutorial.html) 中已有的任意流形，<span class="math-inline">f: M &rarr; R</span>、<span class="math-inline">h: M &rarr; R<sup>l</sup></span> 和 <span class="math-inline">g: M &rarr; R<sup>m</sup></span> 均为光滑函数。

<div class="link-row"><a class="pill-link" href="https://github.com/GALVINLAI/RIPM">代码与说明</a><a class="pill-link" href="https://manoptjl.org/stable/solvers/interior_point_Newton/">Manopt.jl 实现</a></div>

参考文献：Zhijian Lai, Akiko Yoshise. *Riemannian Interior Point Methods for Constrained Optimization on Manifolds*. Journal of Optimization Theory and Applications, 201, 433--469, 2024.
:::
